// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: shape/v1/shape.proto

package shape

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TrianglePerimeterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SideA uint32 `protobuf:"varint,1,opt,name=sideA,proto3" json:"sideA,omitempty"`
	SideB uint32 `protobuf:"varint,2,opt,name=sideB,proto3" json:"sideB,omitempty"`
	SideC uint32 `protobuf:"varint,3,opt,name=sideC,proto3" json:"sideC,omitempty"`
}

func (x *TrianglePerimeterRequest) Reset() {
	*x = TrianglePerimeterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_v1_shape_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrianglePerimeterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrianglePerimeterRequest) ProtoMessage() {}

func (x *TrianglePerimeterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shape_v1_shape_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrianglePerimeterRequest.ProtoReflect.Descriptor instead.
func (*TrianglePerimeterRequest) Descriptor() ([]byte, []int) {
	return file_shape_v1_shape_proto_rawDescGZIP(), []int{0}
}

func (x *TrianglePerimeterRequest) GetSideA() uint32 {
	if x != nil {
		return x.SideA
	}
	return 0
}

func (x *TrianglePerimeterRequest) GetSideB() uint32 {
	if x != nil {
		return x.SideB
	}
	return 0
}

func (x *TrianglePerimeterRequest) GetSideC() uint32 {
	if x != nil {
		return x.SideC
	}
	return 0
}

type TrianglePerimeterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TrianglePerimeterResponse) Reset() {
	*x = TrianglePerimeterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_v1_shape_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrianglePerimeterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrianglePerimeterResponse) ProtoMessage() {}

func (x *TrianglePerimeterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shape_v1_shape_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrianglePerimeterResponse.ProtoReflect.Descriptor instead.
func (*TrianglePerimeterResponse) Descriptor() ([]byte, []int) {
	return file_shape_v1_shape_proto_rawDescGZIP(), []int{1}
}

func (x *TrianglePerimeterResponse) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_shape_v1_shape_proto protoreflect.FileDescriptor

var file_shape_v1_shape_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x5c, 0x0a, 0x18, 0x54, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x69,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x69, 0x64, 0x65, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x69, 0x64,
	0x65, 0x41, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x64, 0x65, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x73, 0x69, 0x64, 0x65, 0x42, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x64, 0x65,
	0x43, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x69, 0x64, 0x65, 0x43, 0x22, 0x31,
	0x0a, 0x19, 0x54, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x32, 0x67, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x5e, 0x0a, 0x11, 0x54, 0x72,
	0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x22, 0x2e, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x69, 0x61, 0x6e,
	0x67, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x37, 0x0a, 0x0e, 0x63, 0x6f,
	0x6d, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x42, 0x0c, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0b, 0x73, 0x68,
	0x61, 0x70, 0x65, 0x3b, 0x73, 0x68, 0x61, 0x70, 0x65, 0xaa, 0x02, 0x07, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shape_v1_shape_proto_rawDescOnce sync.Once
	file_shape_v1_shape_proto_rawDescData = file_shape_v1_shape_proto_rawDesc
)

func file_shape_v1_shape_proto_rawDescGZIP() []byte {
	file_shape_v1_shape_proto_rawDescOnce.Do(func() {
		file_shape_v1_shape_proto_rawDescData = protoimpl.X.CompressGZIP(file_shape_v1_shape_proto_rawDescData)
	})
	return file_shape_v1_shape_proto_rawDescData
}

var file_shape_v1_shape_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shape_v1_shape_proto_goTypes = []interface{}{
	(*TrianglePerimeterRequest)(nil),  // 0: shape.v1.TrianglePerimeterRequest
	(*TrianglePerimeterResponse)(nil), // 1: shape.v1.TrianglePerimeterResponse
}
var file_shape_v1_shape_proto_depIdxs = []int32{
	0, // 0: shape.v1.Shape.TrianglePerimeter:input_type -> shape.v1.TrianglePerimeterRequest
	1, // 1: shape.v1.Shape.TrianglePerimeter:output_type -> shape.v1.TrianglePerimeterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shape_v1_shape_proto_init() }
func file_shape_v1_shape_proto_init() {
	if File_shape_v1_shape_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shape_v1_shape_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrianglePerimeterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shape_v1_shape_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrianglePerimeterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shape_v1_shape_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shape_v1_shape_proto_goTypes,
		DependencyIndexes: file_shape_v1_shape_proto_depIdxs,
		MessageInfos:      file_shape_v1_shape_proto_msgTypes,
	}.Build()
	File_shape_v1_shape_proto = out.File
	file_shape_v1_shape_proto_rawDesc = nil
	file_shape_v1_shape_proto_goTypes = nil
	file_shape_v1_shape_proto_depIdxs = nil
}
